/// Map drum names to General MIDI percussion note numbers.
pub fn drum_name_to_midi(name: &str) -> u8 {
    match name.to_lowercase().as_str() {
        "kick" | "bd" => 36,
        "snare" | "sd" => 38,
        "rimshot" | "rim" => 37,
        "clap" | "cp" => 39,
        "hihat" | "hh" | "closehat" | "ch" => 42,
        "openhat" | "oh" => 46,
        "pedal" => 44,
        "ride" | "rd" => 51,
        "crash" | "cr" => 49,
        "tom1" => 50,
        "tom2" => 47,
        "tom3" => 45,
        "cowbell" | "cb" => 56,
        "tambourine" | "tamb" => 54,
        "cabasa" => 69,
        "maracas" => 70,
        "shaker" => 70,
        "clave" => 75,
        "woodblock" | "wb" => 76,
        "triangle" | "tri" => 81,
        "guiro" => 73,
        _ => 0, // 0 = not a drum
    }
}

/// Canonical instrument names for UI dropdowns, in GM program order.
pub const GM_INSTRUMENT_NAMES: &[&str] = &[
    "piano", "bright piano", "electric piano", "harpsichord", "clavinet",
    "celesta", "glockenspiel", "music box", "vibraphone", "marimba",
    "xylophone", "tubular bells", "dulcimer",
    "organ", "reed organ", "accordion", "harmonica", "bandoneon",
    "nylon guitar", "acoustic guitar", "jazz guitar", "electric guitar",
    "muted guitar", "overdriven guitar", "distortion guitar",
    "bass", "electric bass", "pick bass", "fretless bass", "slap bass", "synth bass",
    "violin", "viola", "cello", "contrabass",
    "tremolo strings", "pizzicato strings", "harp", "timpani",
    "strings", "slow strings", "synth strings",
    "choir", "voice", "synth voice", "orchestra hit",
    "trumpet", "trombone", "tuba", "muted trumpet", "french horn", "brass", "synth brass",
    "soprano sax", "alto sax", "tenor sax", "baritone sax",
    "oboe", "english horn", "bassoon", "clarinet",
    "piccolo", "flute", "recorder", "pan flute", "whistle", "ocarina",
    "square lead", "saw lead", "pad", "warm pad", "polysynth",
    "sitar", "banjo", "shamisen", "koto", "kalimba", "bagpipe", "fiddle",
    "steel drum",
    "drums",
];

/// Map instrument name to General MIDI program number.
pub fn gm_program_from_name(name: &str) -> u8 {
    gm_program_from_name_checked(name).unwrap_or(0)
}

/// Map instrument name to General MIDI program number, returning `None` for unknown names.
pub fn gm_program_from_name_checked(name: &str) -> Option<u8> {
    Some(match name.to_lowercase().as_str() {
        "piano" | "acoustic grand" | "acoustic grand piano" | "grand piano" => 0,
        "bright piano" => 1,
        "electric piano" | "epiano" | "rhodes" => 4,
        "harpsichord" => 6,
        "clavinet" | "clav" => 7,
        "celesta" => 8,
        "glockenspiel" => 9,
        "music box" => 10,
        "vibraphone" | "vibes" => 11,
        "marimba" => 12,
        "xylophone" => 13,
        "tubular bells" => 14,
        "dulcimer" => 15,
        "organ" | "church organ" => 19,
        "reed organ" => 20,
        "accordion" => 21,
        "harmonica" => 22,
        "bandoneon" => 23,
        "nylon guitar" | "classical guitar" => 24,
        "acoustic guitar" | "steel guitar" => 25,
        "jazz guitar" => 26,
        "electric guitar" | "clean guitar" => 27,
        "muted guitar" => 28,
        "overdriven guitar" => 29,
        "distortion guitar" | "distortion" => 30,
        "bass" | "acoustic bass" => 32,
        "electric bass" | "finger bass" => 33,
        "pick bass" => 34,
        "fretless bass" => 35,
        "slap bass" => 36,
        "synth bass" => 38,
        "violin" => 40,
        "viola" => 41,
        "cello" => 42,
        "contrabass" | "double bass" => 43,
        "tremolo strings" => 44,
        "pizzicato strings" => 45,
        "harp" => 46,
        "timpani" => 47,
        "strings" | "string ensemble" => 48,
        "slow strings" => 49,
        "synth strings" => 50,
        "choir" | "aah" => 52,
        "voice" => 53,
        "synth voice" => 54,
        "orchestra hit" => 55,
        "trumpet" => 56,
        "trombone" => 57,
        "tuba" => 58,
        "muted trumpet" => 59,
        "french horn" | "horn" => 60,
        "brass" | "brass section" => 61,
        "synth brass" => 62,
        "soprano sax" => 64,
        "alto sax" | "sax" => 65,
        "tenor sax" => 66,
        "baritone sax" => 67,
        "oboe" => 68,
        "english horn" => 69,
        "bassoon" => 70,
        "clarinet" => 71,
        "piccolo" => 72,
        "flute" => 73,
        "recorder" => 74,
        "pan flute" => 75,
        "whistle" => 78,
        "ocarina" => 79,
        "square lead" => 80,
        "saw lead" | "synth lead" => 81,
        "pad" => 88,
        "warm pad" => 89,
        "polysynth" => 90,
        "sitar" => 104,
        "banjo" => 105,
        "shamisen" => 106,
        "koto" => 107,
        "kalimba" => 108,
        "bagpipe" => 109,
        "fiddle" => 110,
        "steel drum" => 114,
        "drums" | "percussion" | "drum kit" => 0, // channel 9 handles this
        _ => return None,
    })
}
